### ISSUE TITLE
InteractivePlot document.querySelectorAll('div') not pointing to the correct div

### ISSUE THREAD

**Issue by floriandorre** [jMetal/jMetalPy#103]
Hi,

It seems that the HTML file generated by `export_to_html()` is not using the right div for the event `myPlot.on('plotly_click', function(data)`

The plot itself is embed in a div that does not propagate the click to the plotly graph.

Changing the query selector from `var myPlot = document.querySelectorAll('div')[0];` to `var myPlot = document.querySelectorAll('div')[1];` would fix the issue and the pop up describing the closest solution would work again. But maybe targeting the div by looking at the class name **plotly-graph-div** would also be a good solution.

Best regards

**Comment by ajnebro** [comment]
Hi.
  Thanks for reporting the issue.


Regards,

Antonio
