### ISSUE TITLE
Can a PSO algorithm run a mixed variable problem?

### ISSUE THREAD

**Issue by ryanstwrt** [jMetal/jMetalPy#104]
Hello, I am currently using your SPEA2 and SMPSO algorithms for comparison with a MOO algorithm that I am developing. I am testing each algorithm with both continuous and discrete problems. I've got SPEA2 running just fine, but I am not able to get SMPSO to run. The problem uses one discrete variable, and two continuous variables. I believe this may be a limitation of the algorithm its self, but wanted to double check with you all. Thanks a lot, I really appreciate your work in setting up this module.

**Comment by ajnebro** [comment]
Hi.
  In general, PSO algorithms, such as SMPSO, are intended to solve continuous problems.


Antonio

**Comment by ryanstwrt** [comment]
Hi Antonio,

It seemed like that was the case. Thank you for verifying.
