### ISSUE TITLE
Eliminate Duplicate Solutions

### ISSUE THREAD

**Issue by sebhan2** [jMetal/jMetalPy#105]
Hello, is there a way to eliminate duplicate solutions or a procedure to insure mutation only produces solutions which are not present in the current parent population?

If this feature does not exist, I had the idea to modify the `reproduction` function in the `GeneticAlgorithm` class in my implementation or would you recommend an alternative approach?

I am working on a combinatorial optimization problem and duplicates are quite likely.

Thanks.

**Comment by ajnebro** [comment]
If your problem produces many duplicates an approach is to keep a tabu list, so that you can check in the reproduction step whether a new solution is in fact new or a duplicat one.
