### ISSUE TITLE
Which algorithm to use?

### ISSUE THREAD

**Issue by Student-need-help** [jMetal/jMetalPy#111]
Hello there,

this algorithm library here seems to be an awesome project with a lot of opportunities. But how can I choose, which algorithm fits the best for my problem? ( In my case multi-objective)

Is there an easy way or a document how to decide?

Thanks in advance!

**Comment by ajnebro** [comment]
Hi.
  That question is an open and active research line. See for example https://ieeexplore.ieee.org/document/9003018 and https://ieeexplore.ieee.org/document/8733017.

  In jMetal we provide some support for automatic parameter tuning (http://lopez-ibanez.eu/doc/NebLopBarGar2019gecco.pdf), but this feature is not available in jMetalPy.

**Comment by Student-need-help** [comment]
Thank you for your answer! I was hoping to find a simple guideline, but unsurprisingly this research area ist too new and dynamic for simple procedures. But your literature suggestion was really helpful!
