### ISSUE TITLE
How to change evaluation on NSGA2?

### ISSUE THREAD

**Issue by Andreas-SM** [jMetal/jMetalPy#129]
All of the `Evaluator` classes seem to perform sequential evaluation of some kind, i.e. individuals of the population are evaluated one at a time by the objective function. Is there a way to pass the entire population at once to the objective function (as a `numpy.array` or `pandas.DataFrame`)  so as to reduce NSGA2's total computation time per generation?

**Comment by ajnebro** [comment]
Hi.
  There are several subclasses of `Evaluator` that computes the evaluations in parallel: `MultiprocessEvaluator`, `SparkEvaluator` and `DaskEvaluator`.


Antonio

**Comment by Andreas-SM** [comment]
Hello Antonio, 

I was actually hoping to pass a matrix containing all members of the population to the objective function, so as to make only one evaluation instead of many in parallel. I managed to do solve the problem by creating a new `Evaluator` class and subclass and using it on a slightly different version of the `GeneticAlgorithm` and `NSGA2` classes.
