### ISSUE TITLE
TypeError in PolynomialMutation and SBXCrossover

### ISSUE THREAD

**Issue by franzscheuer** [jMetal/jMetalPy#147]
I came across a small bug in the implementation of **PolynomialMutation** and **SBXCrossover**.

Both use `pow(...)` multiple times. Sometimes the exponent is between 0 and 1 by default. Therefore, complex numbers are introduced if the base is negative and a **TypeError** occurs. 

My solution proposal is to add `abs(...)` around the base of the `deltaq` computation in `PolynomialMutation` (line 74 and 78) and around the base of the `betaq` computation in `SBXCrossover` (line 173, 175, 182 and 184).

**Comment by franzscheuer** [comment]
Note: I just noticed the line numbers are off by a few lines in the original post.

**Comment by ajnebro** [comment]
Hi.
  I have never found such situations when using polynomial mutation and SBX crossover. What distribution index values are you using?


Antonio

**Comment by franzscheuer** [comment]
Hi,

for example let's look at the following code-snipet:

betaq = pow(rand*alpha, (1.0/(self.distribution_index + 1.0)))

For any distribution_index -2 > x > 0 there is no problem, since the exponent will not be a fraction value between -1 and 1.

But anything else will result in a value between -1 and 1. And any value to the power of such a value, will be interpreted as root. And the root of a negative number is a complex number.

**Comment by ajnebro** [comment]
I have used distribution index values within the range (5.0, 400.0).

**Comment by ajnebro** [comment]
I've applied those operators in many studies in the last 15 years and I have never had an error related to complex numbers in pow(), so this issue is intrigues me.

**Comment by franzscheuer** [comment]
I see your point. But mathematically it makes sense (in my opinion) to add abs(). I don't always get a negative base, but sometimes.

**Comment by ajnebro** [comment]
The issue is to decide that, if you get a negative base, that should be considered as an error or as a valid value. If it is the former, using abs() would hide the error, which could be very difficult to find later if an algorithms yields unexpected results.
