### ISSUE TITLE
SPXCrossover doesn't work with number of variables > 1

### ISSUE THREAD

**Issue by sergiosilvarubio** [jMetal/jMetalPy#149]
Hi. I did several tests with different numbers of variables and the following always happens:

For example, number of variables = 3 (and number of bits = 8)

Parent 0
[**True, True, True**, False, False, True, False, False]
[_False, True, False, True, False, False, False, True_]
[_False, False, True, False, True, True, True, False_]

Parent 1
[True, False, True, **True, True, False, False, False**]
[False, True, True, True, True, True, True, False]
[False, True, False, True, False, True, True, False]

Offspring 0
[**True, True, True, True, True, False, False, False**]
[False, True, True, True, True, True, True, False]
[False, True, False, True, False, True, True, False]

Offspring 1
[True, False, True, False, False, True, False, False]
[_False, True, False, True, False, False, False, True_]
[_False, False, True, False, True, True, True, False_]

Values in bold: Parent 0 and Parent 1 contribute in the first variable of Offspring 0 (Same idea for Offspring 1)

Values in italics: Then the other variables of Parent 0 go to Offspring 1 without any changes.

I would expect that the same logic for creating the first variable applies to others. Is this correct or am I wrong?

**Comment by ajnebro** [comment]
Hi.
  The SPXCrossover assumes that all the variables lead to a single bit string (i.e., the bit strings of all the variables are concatenated). Taking this into account, the example you include seems to work as expected.

**Comment by sergiosilvarubio** [comment]
> Hi.
>   The SPXCrossover assumes that all the variables lead to a single bit string (i.e., the bit strings of all the variables are concatenated). Taking this into account, the example you include seems to work as expected.
> 
> 
> 

Thank you for the quick answer, now it's very clear to me. Thank you very much again and great project!
