### ISSUE TITLE
Question about function evaluations

### ISSUE THREAD

**Issue by mich0611** [jMetal/jMetalPy#150]
I'm not sure about how to count the **function evaluations** for MOEAs.
In NSGAII, the function evaluations seems to be dependent on the population size. 
(self.evaluations += self.offspring_population_size). 
So my question is : the **function evaluations** have nothing to do with the objective number,
or something else in the algorithm ? Thank you!

**Comment by ajnebro** [comment]
Hi.
  The number of funtion evaluations counts the number of times that the functions of a problem are evaluated. It does not take into accout that a problem could have 1, 2 or more objectives.

  In a generational GA, both the population and the offpspring population have the same size, but in a steady-state one the size of the offspring population size is one. As the new generated solutions are those in the offpspring population, the evaluation counter is increased by the offpspring population size.

**Comment by F-U-Njoku** [comment]
Hi @ajnebro ,
For binary problems , must the number of maximum evaluation be less than or equal to the population size?
cos i get an error when i do this.
Thank you!

![Screenshot from 2022-10-29 12-01-34](https://user-images.githubusercontent.com/40646516/198825450-bf4d4133-85c7-4b41-ae28-4760081bf563.png)

![Screenshot from 2022-10-29 12-04-12](https://user-images.githubusercontent.com/40646516/198825583-2f01f4a5-5910-4fc7-b79d-b78e10d99d49.png)
