### ISSUE TITLE
Integer variables and SBXCrossover

### ISSUE THREAD

**Issue by yhamadi75** [jMetal/jMetalPy#160]
Hello,

I have an Integer problem, which uses the SBXCrossover operator. However, I have to encode through Float variables since IntegerSBXCrossover operator is not available for import (not in jMetalPy/jmetal/operator/__init__.py). Is there a reason for that? Should I just hack that file to allow export?

Is there a perf/result difference in:
- using Floats to encode Integers and applying SBXCrossover for Floats
- using Integers and applying for IntegerSBXCrossover for Integers

Using latest release to date 1.5.7, thanks for clarifying!

- y

**Comment by ajnebro** [comment]
> IntegerSBXCrossover operator is not available for import (not in jMetalPy/jmetal/operator/init.py). Is there a reason for that? 

It seems that we forgot to include it :(

> Should I just hack that file to allow export?

We are going to fix this, but in the meantime feel free to make any changes you need to make it work.

> Is there a perf/result difference in:
>
>using Floats to encode Integers and applying SBXCrossover for Floats
>using Integers and applying for IntegerSBXCrossover for Integers

I have not made any study comparing both approaches so I'm afraid I cannot help. In principle, using integers should made the algorithms run faster (I don't know to what extent) and I suspect that the results should be similar.

**Comment by yhamadi75** [comment]
Thanks Antonio for the quick reply, and happy to help correcting a small thing :)
