### ISSUE TITLE
defining new problems

### ISSUE THREAD

**Issue by makgul1** [jMetal/jMetalPy#165]
Hi,

I am following the tutorial provided on the following website:

https://jmetal.github.io/jMetalPy/tutorials/problem.html

However, I get the following error

TypeError: Can't instantiate abstract class SubsetSum with abstract methods name, number_of_constraints, number_of_objectives, number_of_variables.

Although the abstract methods are implemented as suggested by the tutorial code; I got the above error. Could you please help?

Thank you

**Comment by ajnebro** [comment]
Hi.
  The documentation for that problem is outdated.  You can find the current implementation of the SubsetSum problem here: https://github.com/jMetal/jMetalPy/blob/c6007cad8aa0e12ddd6f8d2f749e3d2cfb6b1367/jmetal/problem/singleobjective/unconstrained.py#L123C30-L123C30

Antonio

**Comment by ajnebro** [comment]
Hi.
