### ISSUE TITLE
DistributedNSGAII vs NSGAII+DaskEvaluator

### ISSUE THREAD

**Issue by yhamadi75** [jMetal/jMetalPy#178]
Hello,
I'd like to understand the differences between the example version of NSGAII which uses Dask evaluator:
 algorithm = NSGAII(
        problem=problem,
        population_size=10,
        offspring_population_size=10,
        mutation=PolynomialMutation(probability=1.0 / problem.number_of_variables, distribution_index=20),
        crossover=SBXCrossover(probability=1.0, distribution_index=20),
        population_evaluator=DaskEvaluator(),
        termination_criterion=StoppingByEvaluations(max_evaluations=max_evaluations),
    )
and the Distributed NSGAII version which does not
    algorithm = DistributedNSGAII(
        problem=problem,
        population_size=100,
        mutation=PolynomialMutation(probability=1.0 / problem.number_of_variables(), distribution_index=20),
        crossover=SBXCrossover(probability=1.0, distribution_index=20),
        termination_criterion=StoppingByEvaluations(max_evaluations=max_evaluations),
        number_of_cores=ncores,
        client=client,
    )

Both require Dask. My understanding is that the DaskEvaluator splits solution evaluation into pieces given to workers, and I guess the Distributed NSGAII version does the same in its own way. There must be a difference I miss between these two versions?

Thanks for clarifying!

**Comment by ajnebro** [comment]
Hi.
  An evaluator is an object that evaluates a list of solutions, either sequentially or in parallel (as in the case of the DaskEvaluator). The parallel model is always synchronous, so the behaviour of the algorithm does not change.

  In the case of `DistributedNSGAII` we use an asynchronous master-worker parallel model, which potentially improves parallel performance but at the cost of having to redesign the NSGA-II algorithm to adopt it.

 


Antonio

**Comment by yhamadi75** [comment]
Thanks for clarifying Antonio. I can see why having two versions.

**Comment by yhamadi75** [comment]
Hi Antonio,
A quick question: 
In the distributed_nsgaii_with_dask.py example, the number of workers is explicitly given by setting up the Dask client: # setup Dask client
    client = Client(LocalCluster(n_workers=10)).

On the other hand, in the synchronous nsgaii example, it is not stated, the Dask evaluator is just passed as a parameter to the algorithm:         population_evaluator=DaskEvaluator().

How can we decide for number of workers in for synchronous nsgaii?

Thanks
