### ISSUE TITLE
question about __dominance_test

### ISSUE THREAD

**Issue by shambakey1** [jMetal/jMetalPy#21]
Hi
For the attached link, should the test be "best_is_one += 1" instead of "best_is_one = 1"? because the later test will just change (not increment) the "best_is_one" for each objective?
The same question applies for the "best_is_two = 1" also.

Regards

https://github.com/jMetal/jMetalPy/blob/6df9fa2a3a15e556f2bc6e58377781251a741949/jmetal/util/comparator.py#L134

**Comment by ajnebro** [comment]
The test check is not correct, but not for the reason you point out. There is no need to increment the `best_is_one` variable.   

I have just updated the repository.

**Comment by shambakey1** [comment]
Thank you
