### ISSUE TITLE
Question about updating leaders

### ISSUE THREAD

**Issue by shambakey1** [jMetal/jMetalPy#22]
Hi

Why is each swarm particle added to the leaders group?

Regards

https://github.com/jMetal/jMetalPy/blob/6df9fa2a3a15e556f2bc6e58377781251a741949/jmetal/algorithm/multiobjective/smpso.py#L142

**Comment by ajnebro** [comment]
The leader archive contains the non-dominated solutions found so far, so every new particle is added to it.

Please, take into account that the implementation of SMPSO is not finished yet.

**Comment by shambakey1** [comment]
Thank you
