### ISSUE TITLE
size of examined solutions

### ISSUE THREAD

**Issue by shambakey1** [jMetal/jMetalPy#23]
Hi

If the leaders group holds all swarm particles (as done by initialize_global_best() and update_global_best()), then why the attached line select only 2 random solutions from the leaders (i.e., the whole swarm) to determine the global best solution?

Regards

https://github.com/jMetal/jMetalPy/blob/6df9fa2a3a15e556f2bc6e58377781251a741949/jmetal/algorithm/multiobjective/smpso.py#L160

**Comment by ajnebro** [comment]
Hi @shambakey1 

Sorry for not responding to your question before; I have just seen it. The answer is that the external archive stores all the non-dominated solutions found during the search but it has a bounded size, so some of the them are removed when the archive is full. 

The leader selection strategy in SMPSO consists in selecting randomly two solutions from the archive and taking the one that dominates the other (o any of them if both are non-dominated).

**Comment by shambakey1** [comment]
Many thanks
