### ISSUE TITLE
Do you still have plans to develop python version?

### ISSUE THREAD

**Issue by babyfiv5** [jMetal/jMetalPy#24]
I recently learned about Jmetal and I only familiar with the python language, but I found that python version  lack of many algorithms and problems （in fact, only nsga2 algorithm and smpso algorithm joined）. Do you have plans to update the python version  with the java version, or hope that we develop these algorithms and problems by ourself ？

**Comment by ajnebro** [comment]
Hi. My plan is to add progressively algorithms to jMetalPy, but in any case I don't intend to rewrite all the jMetal code in Python. NSGA-II is working and SMPSO is not still finished; MOEA/D is the next technique to be included.

I'm the only developer of this project for now, and that's the reason why it is going very slow. Of course, contributions are welcome.
