### ISSUE TITLE
Configure number of runs in a experiment

### ISSUE THREAD

**Issue by moar82** [jMetal/jMetalPy#26]
Hello, I am using the module NSGAII-SMPSO for ZDT1.py for setup an experiment, and I could not find the parameter for setup the number of runs.  In JMetal for Java there is an option to select the number or runs, and given that metaheuristics are non-deterministic, it is desirable to setup the number of runs  of an experiment.  I made a keyword search on the repository, and I could not found the words runs. Hence, I wonder if I am missing something, or number of runs feature is not available in JMetalPy?

Regards.

**Comment by benhid** [comment]
Hello @moar82! You are right, there is no way to set the number of runs for any given experiment for now. You can always encapsulate the experiment in a _for_ loop to replicate that feature.

Note that the module `laboratory` is not finished yet, so there are still a lot of missing features (this one in particular will be included in the next iteration of jMetalPy). Thanks!

**Comment by benhid** [comment]
Now it is possible to setup the number of runs (see 419f0e5) :smile:
Examples were also updated!
