### ISSUE TITLE
Problem after install

### ISSUE THREAD

**Issue by ploub** [jMetal/jMetalPy#36]
Hello,
Thank you for your work !
I installed version 0.9 (python3.7.2) (with pip and git) all ok.
I tried to run an example code from documentation and at execution I have an exception on jmetal.component : ModuleNotFoundError: No module named 'jmetal.component'

Actually, there is no subfolder component in the jmetal folder...
Is it an error in the doc or in the installation scripts? 
Thanks for all !

**Comment by ploub** [comment]
I was on master branch.
I looked on antonio branch and there is a folder jmetal/component 
Maybe it is missing in master branch ?

**Comment by benhid** [comment]
The documentation is a little bit outdated (we didn't have time to update it yet), so some content may be missing and/or incorrect. There are multiples examples within the `examples` folder which you can use for now. 

Sorry for the inconvenience!

**Comment by benhid** [comment]
The documentation is a little bit outdated (we didn't have time to update it yet), so some content may be missing and/or incorrect. There are multiples examples within the `examples` folder which you can use for now. 

Sorry for the inconvenience!

**Comment by ploub** [comment]
No problem (we all have the same issue with documentation ;) )
It seems to work fine, thank you very much, great project, great work !

(you have still one call to jmetal.component that will fail in the multiobjective "smpso_srinivas_on_the_fly.py" example).
