### ISSUE TITLE
NSGAII 

### ISSUE THREAD

**Issue by milagoranova** [jMetal/jMetalPy#40]
Hi,

I am new to this framework so not sure if there is a problem on my side, but whenever I'm trying to run any of the NSGAII examples I get the following errors:

> C:\Users\---\PycharmProjects\jMetal\venv\Scripts\python.exe C:/Users/---/PycharmProjects/jMetal/Main.py
> C:\Users\---\PycharmProjects\jMetal\venv\lib\site-packages\dask\config.py:161: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
>   data = yaml.load(f.read()) or {}
> Traceback (most recent call last):
>   File "C:/Users/---/PycharmProjects/jMetal/Main.py", line 2, in <module>
>     from jmetal.algorithm.multiobjective.nsgaii import NSGAII
>   File "C:\Users\---\PycharmProjects\jMetal\venv\lib\site-packages\jmetal\algorithm\multiobjective\nsgaii.py", line 4, in <module>
>     from distributed import as_completed, Client
>   File "C:\Users\---\PycharmProjects\jMetal\venv\lib\site-packages\distributed\__init__.py", line 5, in <module>
>     from .actor import Actor, ActorFuture
>   File "C:\Users\---\PycharmProjects\jMetal\venv\lib\site-packages\distributed\actor.py", line 4, in <module>
>     from .client import Future, default_client
>   File "C:\Users\---\PycharmProjects\jMetal\venv\lib\site-packages\distributed\client.py", line 49, in <module>
>     from .batched import BatchedSend
>   File "C:\Users\---\PycharmProjects\jMetal\venv\lib\site-packages\distributed\batched.py", line 10, in <module>
>     from .core import CommClosedError
>   File "C:\Users\---\PycharmProjects\jMetal\venv\lib\site-packages\distributed\core.py", line 20, in <module>
>     from .comm import (
>   File "C:\Users\---\PycharmProjects\jMetal\venv\lib\site-packages\distributed\comm\__init__.py", line 27, in <module>
>     _register_transports()
>   File "C:\Users\---\PycharmProjects\jMetal\venv\lib\site-packages\distributed\comm\__init__.py", line 18, in _register_transports
>     from . import inproc
>   File "C:\Users\---\PycharmProjects\jMetal\venv\lib\site-packages\distributed\comm\inproc.py", line 15, in <module>
>     from ..protocol import nested_deserialize
>   File "C:\Users\---\PycharmProjects\jMetal\venv\lib\site-packages\distributed\protocol\__init__.py", line 7, in <module>
>     from .cuda import cuda_serialize, cuda_deserialize
>   File "C:\Users\---\PycharmProjects\jMetal\venv\lib\site-packages\distributed\protocol\cuda.py", line 5, in <module>
>     from dask.utils import typename
> ImportError: cannot import name 'typename' from 'dask.utils' (C:\Users\---\PycharmProjects\jMetal\venv\lib\site-packages\dask\utils.py) 

My version of jmetalpy is 0.9.0 and this happens only when I'm running the NSGAII examples.

Thank you in advance for your help.

**Comment by benhid** [comment]
It seems that there is some problem with Dask. jMetalPy requires `dask[complete]==1.0.0`. Can you verify which version of Dask is installed on your environment?

**Comment by milagoranova** [comment]
> It seems that there is some problem with Dask. jMetalPy requires `dask[complete]==1.0.0`. Can you verify which version of Dask is installed on your environment?

Thanks a lot for the quick reply. I had version 1.0. I just updated it to 2.0 and that seemed to solve it.
