### ISSUE TITLE
Documentation is misalligned with code 

### ISSUE THREAD

**Issue by vedina** [jMetal/jMetalPy#41]
The examples at https://jmetalpy.readthedocs.io/en/latest/examples.html do not work.  

Apparently they were written for different version than 0.9.0 and need considerable guessing by a newcomer to ever get some demo code to work.

**Comment by benhid** [comment]
You are absolutely right, we are working on that. As for now, I will update the README to reference the examples located in the [`examples` folder](https://github.com/jMetal/jMetalPy/blob/master/examples/) within the repository instead of the ones from the docs.
