### ISSUE TITLE
Only old versions up to 0.9.0 available on pip

### ISSUE THREAD

**Issue by ttusar** [jMetal/jMetalPy#44]
While the latest jmetalpy version here is 1.5.0, the latest one that can be installed through pip is 0.9.0. I don't know how pip handles version updates - is there something you can do about it?

**Comment by benhid** [comment]
The latest version (1.5.0) have now been uploaded to pypi (thank you for the reminder!):
```
pip install jmetalpy --upgrade
```

**Comment by ttusar** [comment]
Perfect, many thanks!
