### ISSUE TITLE
Permutation Problem

### ISSUE THREAD

**Issue by jacksonpradolima** [jMetal/jMetalPy#45]
Hello,
Could you provide an example for permutation problems?
Moreover, could you update the package in the pip? There are no some parts to create a permutation problem (new solution/crossover/mutation).

Thanks

**Comment by benhid** [comment]
Hello,

I have included one single-objective problem which involves permutation encoding ([Travelling Salesman Problem](https://github.com/jMetal/jMetalPy/blob/master/examples/singleobjective/generational_genetic_algorithm_tsp.py)). Also, jMetalPy have been updated to version 1.5.**1** with some minor fixes ;)

Regards
