### ISSUE TITLE
[Question] How to start NSGA2 algorithm?

### ISSUE THREAD

**Issue by jongyook2** [jMetal/jMetalPy#46]
Hello!

I want to study optimizing algorithms, but i don't have background about optimizing algorithms. Can you give guide for me about what should i do first? 

Thank you in advance.

**Comment by ajnebro** [comment]
Hi.
  jMetalPy is a framework for multi-objective optimization with metaheuristics, so a basic background on this matter is needed to use it. Unfortunately, this place is not the right place to get that background. The issues opened here are devoted to addressing questions, comments, bugs, etc. directly related about jMetalPy; beyond that, they are out of scope.
 
 Anyway, if you want basic bibliography about multi-objective optimazation and metaheuristics, feel free to contact me.

Antonio

**Comment by jongyook2** [comment]
Oh sorry 
Thank you!
