### ISSUE TITLE
Documentation for example visualization appears to have some left-over merge text

### ISSUE THREAD

**Issue by mbelmadani** [jMetal/jMetalPy#48]
In https://github.com/jMetal/jMetalPy/blob/master/docs/source/examples/visualization.rst, there seems to be some left-over merge text:

```
<<<<<<< HEAD .. raw:: html =======

>>>>>>> 52e0b172f0c6d651ba08b961a90a382f0a4b8e0f
```

which causes rendering issue. Noticed on the `readthedocs` site: https://jmetalpy.readthedocs.io/en/latest/examples/visualization.html

**Comment by benhid** [comment]
Hi,

You are right. We are working on a more extended and user friendly documentation, so -as for now- we recommend to take a look at the [examples](https://github.com/jMetal/jMetalPy/tree/master/examples).

Nevertheless, I will fix the rendering right now! Thank you.
