### ISSUE TITLE
implementación de problema genérico

### ISSUE THREAD

**Issue by JansAlbornoz** [jMetal/jMetalPy#51]
Hola estimados, ayer leí el paper y me interesó bastante su proyecto. He estado buscando en la documentación pero no he encontrado algún ejemplo para algún modelo de optimización genérico, como el problema de la mochila o un problema de transporte. ¿Tienen algún ejemplo de como resolver algún problema de optimización genérico a través de las metaheurísticas del framework? Aun no logro encontrar la sintaxis para cargar mi problema de optimización en alguna de las metaheurísticas del framework. Saludos

**Comment by benhid** [comment]
Hola,

En jMetalPy se encuentran incluidas las versiones mono-objetivo del [problema de la mochila](https://jmetal.github.io/jMetalPy/api/problem/singleobjective.html#module-jmetal.problem.singleobjective.knapsack) ([ejemplo](https://github.com/jMetal/jMetalPy/blob/master/examples/singleobjective/steady_state_genetic_algorithm_with_knapsack_problem.py)) y el [TSP](https://jmetal.github.io/jMetalPy/api/problem/singleobjective.html#module-jmetal.problem.singleobjective.tsp) ([ejemplo](https://github.com/jMetal/jMetalPy/blob/master/examples/singleobjective/generational_genetic_algorithm_tsp.py)).

En la documentación también encontrarás una guia sobre [cómo incluir nuevos problemas](https://jmetal.github.io/jMetalPy/tutorials/problem.html) (tomando como ejemplo el problema del _subset sum_).

¡Espero que te sea de utilidad! :)
