### ISSUE TITLE
RandomSearch

### ISSUE THREAD

**Issue by milagoranova** [jMetal/jMetalPy#52]
Hello,

I have implemented a multiobjective problem using RandomSearch the following way:

```
problem = CustomProblem.Problem()
    time_counter = TimeCounter(delay=1)
    time_counter.observable.register(problem)
    time_counter.start()
    max_seconds = 100

    algorithm = RandomSearch(
        problem=problem,
        termination_criterion=StoppingByTime(max_seconds),
    )
    algorithm.observable.register(observer=ProgressBarObserver(max=max_seconds))
    algorithm.run()
```
The version of the package I'm using is 1.5.1.

The code compiles just fine. However, after 100 seconds the process is still running and the ProgressBarObserver is not printed either. I tried implementing StoppingByEvaluations and same happened. I also tried using one of the included in the package problems ZDT1 with both termination criterions and same happened.

I have successfully implemented a few other multi-objective algorithms including NSGA-II, OMOPSO, SMPSO using the same custom problem and everything has run smoothly so far.

I could not find an example of an implementation of RandomSearch in the example folder so apologies if I have just done that incorrectly. I would appreciate some input on why the process does not terminate and results are not generated. 

Thanks in advance,
Mila

**Comment by ajnebro** [comment]
Hi Mila.
  I have revised the implementation of the random search and added an example.

  The algorithm should work now as you intended to use it.


Antonio

**Comment by milagoranova** [comment]
Hi Antonio,

Thank you for the very quick reply.

After your changes my implementation of RandomSearch runs as expected.

Thanks,
Mila
