### ISSUE TITLE
Constraint

### ISSUE THREAD

**Issue by 1017073490** [jMetal/jMetalPy#58]
Hi, I'm come back.
Now, I want to restructure my problem algorithm. I want to know if the moead_lz09.py in examples.multiobjective can run the constraint problem? Because i can run the Srinivas in jmetal.problem directly.
If yes, I can safely refactor the code with reference to the example of Srinivas.
If no, I will choose jMetal instead of jMetalPy.
Thank you.

**Comment by ajnebro** [comment]
Just take a look to the MOEA/D Epsilon algorithm: https://github.com/jMetal/jMetalPy/blob/master/examples/multiobjective/moead_iepsilon_lircmop1.py

**Comment by 1017073490** [comment]
I run your Demo moead_iepsilon_lircmop1.py and there seem no problem, but the files of FUN and VAR has no data. Could you check it and respond to me?
Best wish.

**Comment by ajnebro** [comment]
The example should work now. I have added also an example to solve the Srinivas problem.

**Comment by 1017073490** [comment]
I'm so glad to recive this message. And thank you very much.
