### ISSUE TITLE
Values and variables are not saved to files

### ISSUE THREAD

**Issue by 1017073490** [jMetal/jMetalPy#59]
Thank you for adding some new examples, and I can run the moead_iepsilon_srinivas successfully. I'm going to write my own target function based on this demo. But another moead_iepsilon_lircmop2 still have one problem that there are no results in the files of FUN and VAR.
With best wishes!

**Comment by benhid** [comment]
Try moving the print functions just after the results:

    front = algorithm.get_result()

    print_function_values_to_file(front, 'FUN.' + algorithm.label)
    print_variables_to_file(front, 'VAR.' + algorithm.label)

The interactive plot might be blocking the main thread, so instead of stopping the script's execution just close the figure.
