### ISSUE TITLE
Pareto front tracking

### ISSUE THREAD

**Issue by jjsoper** [jMetal/jMetalPy#60]
Hello,

Is there any functionality in place to track the progress of the non-dominated solution set (i.e. plot number of improvements versus number of function evaluations) for any given algorithm? Specifically, I would like to evaluate the search progress / performance of the NSGA-II as applied to a water quality model optimization that I am running.

Thanks,
Josh

**Comment by benhid** [comment]
Hello,

Take a look [here](https://jmetal.github.io/jMetalPy/tutorials/observer.html). You can create your own observers (e.g., [BasicObserver](https://github.com/jMetal/jMetalPy/blob/master/jmetal/util/observer.py#L51)) to track information about the optimization process.

Antonio.
