### ISSUE TITLE
ModuleNotFoundError (jmetal.util.comparator)

### ISSUE THREAD

**Issue by AshutoshMishraNITIE** [jMetal/jMetalPy#65]
Besides having .py file of comparator in util folder . 
Error of No module named jmetal.util.comparator comes up. how to remove it?

**Comment by benhid** [comment]
Hello,

Latest changes on the repository where not published to pypi, which may be the cause of your problem (did you installed jMetalPy with `pip install jmetalpy`?).

I have released a new version (v1.5.3) of the framework, try reinstalling (should be working now).

Thank you!
