### ISSUE TITLE
Permutation problem operators

### ISSUE THREAD

**Issue by YevheniiSemendiak** [jMetal/jMetalPy#68]
Hello everyone!

I have found out that Operators for permutation Problems (TSP) impose assumption about different 'depth' of Configuration variables.

More concretely, `CXCrossover` and `ScrambleMutation` operate on configuration variables as it is a nested list (e.g. `configuration.variables == [[1,2,3], [1,2,3], ... [1,2,3]]`).

In other hand, `PermutationSwapMutation`, `PMXCrossover` work with configuration.variables as with 'flat lists' (or, just on top level of nested lists).

As the result, it is impossible to use CXCrossover and ScrambleMutation with TSP problem:
![image](https://user-images.githubusercontent.com/32543098/72579891-b6da3080-38da-11ea-9699-a1583beaa129.png)

Is it a bug in implementation, or the intent of these Operators is different?

P.S. Thank you for your framework, I do really like the architecture and code style :+1:

**Comment by YevheniiSemendiak** [comment]
I [have modified](https://github.com/YevheniiSemendiak/jMetalPy/commit/2837195aa2db4980a8c1d51e25631e03c7e4165a) those operators in order to use them while solving the TSP problem.
If you consider such a fix as possible, I would be glad to submit a PR (after fixing related tests).

**Comment by ajnebro** [comment]
Hi.
  I would be great. 


Thanks,

Antonio

**Comment by YevheniiSemendiak** [comment]
Hey @ajnebro,

I have updated the tests, but can not find the `develop` branch in repository (seems like it was deleted after the latest release in #79) therefore, I cannot submit a PR properly.
Could you assist?

Thanks!
