### ISSUE TITLE
Handling of mixed combinatorial problems

### ISSUE THREAD

**Issue by mamrushdi** [jMetal/jMetalPy#69]
Does your framework accommodate mixed combinatorial problems (e.g. facility layout planning problems with integer and real variables)?

**Comment by ajnebro** [comment]
Currently not, but we are working right now (in this branch: https://github.com/jMetal/jMetalPy/tree/feature/mixedSolution) in providing an example of how to do it. 

We hope to have the full example ready soon.

**Comment by ajnebro** [comment]
Hi. We have developed an approach to deal with this issue by providing a `CompositeSolution` class, which can be composed of list of existing solutions. The corresponding `CompositeCrossover` and `CompositeMutation` operators are also provided.

We plan to write the documentation of these clases in the incoming days. Meanwhile, an example is contained in class [`nsgaii_solving_mixed_encoding_problem`](https://github.com/jMetal/jMetalPy/blob/feature/mixedSolution/examples/multiobjective/nsgaii/nsgaii_solving_mixed_encoding_problem.py).
