### ISSUE TITLE
Requiring FloatSolution in SBXCrossover and PolynomialMutation

### ISSUE THREAD

**Issue by ttusar** [jMetal/jMetalPy#78]
Since the change to 1.5.4, `SBXCrossover` and `PolynomialMutation` can only be executed on solutions of the type `FloatSolution`. They fail if they are invoked on solutions of a type that inherits from `FloatSolution`, which, I imagine, is a bug.

**Comment by ajnebro** [comment]
There was a check in the ``execute()`` method of those operators to ensure that the solutions were instances of class ``FloatSolution``, what is the reason of the error you have reported.

Those checks have been replaced by:

``` 
Check.that(issubclass(type(solution), FloatSolution), "Solution type invalid")
```

The changes are already available in the develop branch.

**Comment by ttusar** [comment]
Thanks for the prompt response! Do you plan to update the master with this change in the next days?

**Comment by benhid** [comment]
Hello @ttusar,

A new version of the framework (v1.5.5) has been released to pypi. Also, the master branch of this repository has been updated.

Thank you!

**Comment by ttusar** [comment]
Many thanks!
