### ISSUE TITLE
Derivative free models

### ISSUE THREAD

**Issue by aimanian** [jMetal/jMetalPy#83]
Our models are based on surrogate
models to approximate the computationally expensive objective functions. Hence, derivative information, which is generally unavailable for black-box simulation ob-
jective functions, is not available. I was wondering if your optimization algorithms can handle derivative free models.

**Comment by ajnebro** [comment]
Metaheuristics techniques, such as evolutionary algorithms, particle swarm optimization, etc. are derivative-free optimization algorithms (https://en.wikipedia.org/wiki/Derivative-free_optimization).

**Comment by aimanian** [comment]
Hello, 
Thanks for your reply. Is there any example, for a machine learning based model for model function? Can you please guide me how to solve a simple problem with, for example, a neural network based model function?
