### ISSUE TITLE
get_non_domiated_solutions() seems not return expected pf solutions with 3 objectives

### ISSUE THREAD

**Issue by easyfly007** [jMetal/jMetalPy#85]
Hello, 
thanks for the great tool of jmetalpy and i use it in my optimization problems and it works quite well.
the only issue I observed is that when I run it for 3 objectives optimization,
the function get_non_domiated_solutions() seems didn't return the required  PF result.
it always return 1 PF point no matter how many points the original solutions has.
to find out if this is my usage issue or potentially code risk, I try to look into the jmetalpy code and find that in:
file util/archive.py:

``` 
     def add(self, solution: S) -> bool:
        is_dominated = False
        is_contained = False

        if len(self.solution_list) == 0:
            self.solution_list.append(solution)
            return True
        else:
            number_of_deleted_solutions = 0

            # New copy of list and enumerate
            for index, current_solution in enumerate(list(self.solution_list)):
                is_dominated_flag = self.comparator.compare(solution, current_solution)
                if is_dominated_flag == -1:
                    del self.solution_list[index - number_of_deleted_solutions]
                    number_of_deleted_solutions += 1
                elif is_dominated_flag == 1:
                    is_dominated = True
                    break
                elif is_dominated_flag == 0:
                    if solution.objectives == current_solution.objectives:
                        is_contained = True
                        break

        if not is_dominated and not is_contained:
            self.solution_list.append(solution)
            return True

        return False
```

I am afriad that when del some member in the original list when looping it, it may deleted the unexpeced member there.
I think when during the looping of  enumerate(), it will always get updated the list and then we are iterate the unexpected members

I did some simple test and find the issue:

```
num_deleted = 0
a = [10,11,12, 13, 14]
for i,v in enumerate(a):
    print("")
    print('i =', i, ', v = ', v)
    print('a = ',  a)

    if v % 2 == 0:
        print("condition is true, v {} deleted".format(str(a[i- num_deleted ])))
        del a[i - num_deleted]
    num_deleted += 1

print('finally, a = ', a)

```

what I want is to get the final a = [11, 13], but actually I got is [13, 14]

**Comment by ajnebro** [comment]
Hi @easyfly007.
  I'm running the `nsgaiii_dtlz2.py` program after adding the `get_non_dominated_solutions()` function in this way:

```python

    algorithm.run()
    front = get_non_dominated_solutions(algorithm.get_result())

```

  The front have 92 solutions, which is the expected result. 
  
  How are you using that function, in order to allow us to reproduce the situation where only a solution is returned?

**Comment by easyfly007** [comment]
Hi ajnebro,
below is my reproduce code and data, you need to save the data into a file named all_objectives.csv

hope I am using the function correctly.

many thanks,


```
from jmetal.util.solution import get_non_dominated_solutions
from jmetal.core.solution import  Solution

filename = "./all_objectives.csv"
objectives = []
linenum = 0 
with open(filename, "r") as f:
    lines = f.readlines()
    for line in lines:
        line = line.strip().lower()
        if linenum == 0:
            names = line.split(",")
        else:
            objective = line.split(",")
            objective = [float(x) for x in objective]
            objectives.append(objective)
        linenum += 1
print("")
print("names = ", names)
print("objectives = ")
for objidx, objective in enumerate(objectives):
    print("objidx = ", objidx, ", value = ", objectives)

all_solutions = []
number_of_variables = 4 
number_of_objectives = 3 
for objective in objectives:
    solution = Solution(number_of_variables, number_of_objectives)
    solution.objectives = objectives 
    all_solutions.append(solution)

pf_solutions = get_non_dominated_solutions(all_solutions)
print("all_solutions size = ", len(all_solutions))
print("pf_solutions size = ", len(pf_solutions))

```

and below is the data file of all_objectives；
iqmin,von50,hys50
5.526459811917846e-10,1.1044017818567373,0.20200390236357704
4.649040031707926e-09,1.4083415892243343,0.2748007308873209
6.079827956586957e-10,1.104275573070615,0.2103624517049332
1.1703387806584528e-09,1.353196420253987,0.1818526616245808
3.134974233979557e-09,1.3966204628086514,0.3636218429244531
4.6684550138361015e-09,1.4048347716865561,0.3134072524168081
3.3204227872140253e-09,1.3969231776409012,0.3333666219229492
1.6482119117303786e-09,1.4063434821320795,0.2568765952195531
6.956935503184769e-10,1.1229172038976882,0.22610200698788963
2.6483234588111813e-09,1.402622610468025,0.31578576899185706
2.0380843493566927e-09,1.402324948269576,0.3031108337339208
1.7866957541404399e-09,1.407260008625782,0.27246846330799945
2.0292388077139125e-09,1.2581795958259863,0.35182258170407066
1.0078993883601702e-09,1.2728296289436414,0.3366450606324812
1.6465236559146827e-09,1.401916779550804,0.25830866349855386
8.036167657735518e-10,1.1755700805883553,0.18560003610656628
1.3960640991932755e-09,1.3753418800322428,0.34234326084196415
1.2356829304108664e-09,1.3676359533536437,0.30916273467184757
2.6548095467739573e-09,1.4042430602510882,0.3045012601542963
7.308195983560921e-10,1.1609416183674142,0.224568379023091
3.0027622217944307e-09,1.4045981187653152,0.31695083376816346
6.510552224774739e-10,1.1235247204746297,0.2198741110574948
6.758593494483507e-10,1.1445575185281431,0.19530955885690646
8.123265675814112e-10,1.190833430432861,0.19249668338486714
1.275672350460555e-09,1.3770100388574926,0.3011089540559447
1.0436788498826157e-09,1.28570611338927,0.31860221710011627
1.8423366452283497e-09,1.3979918555435622,0.3213170774936529
1.2814024774093913e-09,1.392581556050541,0.3249674234016766
1.1928907469389332e-09,1.3411887537396583,0.32672579619239195
6.960290207485847e-10,1.129710381663843,0.20294407984002652
9.563222728513102e-10,1.2574871466173814,0.20656249562228512
1.115053517586667e-09,1.2985323154598996,0.27739011159600363
2.0292388077139125e-09,1.2581795958259863,0.35182258170407066
2.859375579036974e-09,1.4067622422570554,0.292590557323688
9.34653777489502e-10,1.234559679234927,0.29356058683328534
9.78236920416313e-10,1.2486608191922035,0.2955991888405759
7.070065118730767e-10,1.1495189574642095,0.18948803837521794
3.3204227872140253e-09,1.3969231776409012,0.3333666219229492
1.275517294261997e-09,1.373987832955956,0.3214077841982512
8.542444815736423e-10,1.1933389527654856,0.2789844112377316
8.925012263196182e-10,1.2093733822442976,0.29787108523898126
1.1775972470625775e-09,1.309311007361528,0.3249859096250125
9.285471886957665e-10,1.232675849951282,0.30015439363914237
8.598957375098381e-10,1.202731200545344,0.2935396832316062
1.5709060754718543e-09,1.3981611283913264,0.31686523748908574
1.8215295249881668e-09,1.4000116883076217,0.31182395282608955
8.768239901965012e-10,1.2162081837627017,0.2851165874718243
7.10698550100126e-10,1.1247192343477839,0.2211249088327457
1.2146399161175923e-09,1.2610136654018422,0.33941285482601335
8.404361343995722e-10,1.2053355539803003,0.1924172707920857
1.2848481373094362e-09,1.289873255053387,0.3348021077326545
1.4809843256175603e-09,1.401908637663458,0.25824392235075294
1.3219681239294665e-09,1.3946753051187737,0.3196153245978861
1.685696202515554e-09,1.3988019636634357,0.3191329555535305
1.3167315494037954e-09,1.3982930238443507,0.2797171453543313
9.522019390810921e-10,1.2470731390946705,0.20322093101862396
5.713971288121142e-10,1.1069788544334251,0.2056110408875661
2.859375579036974e-09,1.4067622422570554,0.292590557323688
5.953088896047281e-10,1.1145425040338435,0.19680683957231765
1.6514997939626884e-09,1.4036090444604825,0.2876289103333116
1.1549181495756353e-09,1.3288969882396096,0.3022518235773648
1.233048275191051e-09,1.3627441296364702,0.32426695365210145
1.1849999144790438e-09,1.3551446726529246,0.2254907622101161
1.1012234193837874e-09,1.2894894045465586,0.33537142984866
1.144194724285928e-09,1.3243144308138037,0.2987430390759809
1.3181443784516226e-09,1.3462812174180552,0.3317879310766603
1.1813069571145178e-09,1.32043126412311,0.3135586835282232
1.161711600568023e-09,1.3088952827475835,0.3312418741732569
9.195243914274754e-10,1.2233935032079721,0.3021319998862634
1.445360885587594e-09,1.3968724050704655,0.34177350726903466
8.240523406643407e-10,1.170725661764812,0.19457723515103464
9.861867459692323e-10,1.2656658025785568,0.2914177193800214
8.666744211351688e-10,1.212151699453524,0.29442622319817024
9.792227956276754e-10,1.2656364108346987,0.29132133073439137
5.94852867431418e-10,1.109064825491569,0.20637674917842017
6.220931813639103e-10,1.1176700364684045,0.19776323357757217
1.1472423980080645e-09,1.3342037933070752,0.293815835388938
7.070065118730767e-10,1.1495189574642095,0.18948803837521794
8.768239901965012e-10,1.2162081837627017,0.2851165874718243
1.1361886255532703e-09,1.3035921358454599,0.3325170324622465
7.744973048572214e-10,1.1734654542145724,0.1830289477078333
1.2208697676968928e-09,1.3371898364942334,0.33212264093499894
9.195243914274754e-10,1.2233935032079721,0.3021319998862634
8.2009455311858e-10,1.1654372828677568,0.19414856399645972
7.77454037823314e-10,1.1927899164061488,0.18380141793301014
1.1284508614269698e-09,1.299109119550595,0.3340687811787376
6.342130143343577e-10,1.1281035076805503,0.1998279247298733
1.1297578091509533e-09,1.3072900439228468,0.2862982920091684
1.1813069571145178e-09,1.32043126412311,0.3135586835282232
1.1788755111341565e-09,1.3433420919776962,0.29967818050122347
7.062461314028048e-10,1.145935134936634,0.19576805398372968
6.238645678211714e-10,1.1197661578109723,0.22482552693094998
1.0436788498826157e-09,1.28570611338927,0.31860221710011627
7.039009826789146e-10,1.1630664105136397,0.18297913834472962
1.119603397080147e-09,1.3056764002969246,0.3037964969433504
1.233048275191051e-09,1.3627441296364702,0.32426695365210145
6.176596447548465e-10,1.1225695231680128,0.19403352036090563
9.522019390810921e-10,1.2470731390946705,0.20322093101862396
9.735947158881068e-10,1.2616565472986845,0.20301462486937383
4.649040031707926e-09,1.4083415892243343,0.2748007308873209

**Comment by easyfly007** [comment]
thanks anjebro,
I will try to reproduce the issue in my optimizations and will post how to reproduce it when I have one.
