### ISSUE TITLE
DifferentialEvolutionCrossover does not support NSGAIII

### ISSUE THREAD

**Issue by DLA94** [jMetal/jMetalPy#94]
When i use DifferentialEvolutionCrossover in NSGA III, the crossover does not work. The "current_individual" of DifferentialEvolutionCrossover isn't assigned in NSGA III or GeneticAlgorithm.

**Comment by DLA94** [comment]
# # #

- [ ] 

- [ ] 

- [ ] 

- [ ]

**Comment by ajnebro** [comment]
You cannot just use the DifferentialEvolutionCrossover in NSGA-III due to the reason you report. A version of NSGA-III should be developed to use this operator.

**Comment by DLA94** [comment]
我已收到您的邮件……
