### ISSUE TITLE
How to use Integer and Float variables in one problem?

### ISSUE THREAD

**Issue by simplexity-kaiou** [jMetal/jMetalPy#95]
How can I mix variables of different types or how can I set which varibles are discrete and which are contiguous like
 [0, 1, 0, 2, 1.2, 0.2, 3.6, 1.5] the first four columns are discrete values and the last four columns are continuous values?

**Comment by ajnebro** [comment]
Are the discrete variable values enclosed in a range values? If so, the simplest way would be to work with real values and round the integer ones when evaluating the solutions.
