### ISSUE TITLE
Why we should use chord diagram?

### ISSUE THREAD

**Issue by Antonio-Nappi** [jMetal/jMetalPy#96]
I understand that the pareto front can be visualised as function of the objective function(s) on the different axes, but why the chord diagram is a good visualization for the pareto front? My question is serious, could you provide an example of chord's diagram utility? As suggestion, could be also the spider plot a good instrument for solutions visualization?

**Comment by benhid** [comment]
Hello,
Each chord in a chord diagram represents a solution of the obtained Pareto front with its objective values (i.e., it is used to visualize solutions independently from each other). Furthermore, the diagram is interactive and allows hovering the mouse over the chart and visualizing relationships among objective values.

Take a look at [this](https://doi.org/10.1016/j.knosys.2017.09.035) paper.

**Comment by Antonio-Nappi** [comment]
Ok, thank you. I'll read the paper you posted.
